import { type Metadata } from "next";

export const siteConfig = {
  name: "Re NextJS Template",
  description: "Generated by create next app",
  url: "",
};

export const buildMetadata = (): Metadata => {
  return {
    title: siteConfig.name,
    description: siteConfig.description,
    alternates: {
      canonical: siteConfig.url,
    },
  };
};
