import { Metadata } from "next";
export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Re NextJS Template",
  description: "Generated by create next app",
  url: "",
};

export const buildMetadata = (): Metadata => {
  return {
    title: siteConfig.name,
    description: siteConfig.description,
  };
};
